"""add users table

Revision ID: 1ec7ec20ca1a
Revises: 819e373c73ce
Create Date: 2026-07-07 08:04:59.863141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ec7ec20ca1a'
down_revision: Union[str, Sequence[str], None] = '819e373c73ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('esusu_contributions', sa.Column('payment_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'esusu_contributions', ['payment_id'])
    op.create_foreign_key(None, 'esusu_contributions', 'payments', ['payment_id'], ['id'], ondelete='RESTRICT')
    op.add_column('esusu_rounds', sa.Column('nomba_transfer_ref', sa.String(), nullable=True))
    op.add_column('traders', sa.Column('payout_bank_code', sa.String(), nullable=True))
    op.add_column('traders', sa.Column('payout_account_number', sa.String(), nullable=True))
    op.add_column('traders', sa.Column('payout_account_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traders', 'payout_account_name')
    op.drop_column('traders', 'payout_account_number')
    op.drop_column('traders', 'payout_bank_code')
    op.drop_column('esusu_rounds', 'nomba_transfer_ref')
    op.drop_constraint(None, 'esusu_contributions', type_='foreignkey')
    op.drop_constraint(None, 'esusu_contributions', type_='unique')
    op.drop_column('esusu_contributions', 'payment_id')
    # ### end Alembic commands ###
