"""add users table

Revision ID: c22080659485
Revises: 
Create Date: 2026-07-03 17:34:09.353630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c22080659485'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('target_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('current_locked_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fulfilled_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('minimum_contributors', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(), nullable=False),
    sa.Column('supplier_account_number', sa.String(), nullable=False),
    sa.Column('supplier_bank_code', sa.String(), nullable=False),
    sa.Column('nomba_transfer_ref', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'FULFILLED', 'REFUNDED', name='poolstatus'), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pool_deadline', 'pools', ['deadline'], unique=False)
    op.create_index('idx_pool_status', 'pools', ['status'], unique=False)
    op.create_table('traders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('stall_number', sa.String(), nullable=False),
    sa.Column('market_name', sa.String(), nullable=False),
    sa.Column('virtual_account_number', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('bank_account_name', sa.String(), nullable=True),
    sa.Column('spendable_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_contributed', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('virtual_account_number')
    )
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trader_id', sa.UUID(), nullable=False),
    sa.Column('pool_id', sa.UUID(), nullable=True),
    sa.Column('entry_type', sa.Enum('SPENDABLE_CREDIT', 'POOL_LOCK', 'POOL_RELEASE_PAYOUT', 'POOL_REFUND', name='entrytype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trader_id', sa.UUID(), nullable=False),
    sa.Column('amount_received', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('nomba_transaction_ref', sa.String(), nullable=False),
    sa.Column('spendable_portion', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('pool_portion', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('pool_id', sa.UUID(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_nomba_transaction_ref'), 'payments', ['nomba_transaction_ref'], unique=True)
    op.create_table('pool_contributions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trader_id', sa.UUID(), nullable=False),
    sa.Column('pool_id', sa.UUID(), nullable=False),
    sa.Column('amount_locked', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('LOCKED', 'RELEASED', 'REFUNDED', name='contributionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trader_id', 'pool_id', name='uq_trader_pool_contribution')
    )
    op.create_index('idx_pool_contributions_pool', 'pool_contributions', ['pool_id'], unique=False)
    op.create_index('idx_pool_contributions_status', 'pool_contributions', ['status'], unique=False)
    op.create_index('idx_pool_contributions_trader', 'pool_contributions', ['trader_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_pool_contributions_trader', table_name='pool_contributions')
    op.drop_index('idx_pool_contributions_status', table_name='pool_contributions')
    op.drop_index('idx_pool_contributions_pool', table_name='pool_contributions')
    op.drop_table('pool_contributions')
    op.drop_index(op.f('ix_payments_nomba_transaction_ref'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('ledger_entries')
    op.drop_table('traders')
    op.drop_index('idx_pool_status', table_name='pools')
    op.drop_index('idx_pool_deadline', table_name='pools')
    op.drop_table('pools')
    # ### end Alembic commands ###
